added bookshop tags
BenjaminNeustadt/OPEN-BOOK pull request #15
Opened 2022-08-03 15:23 UTC by MalikOJBS

Added tags and test for tags

2022-08-03 23:16 UTC, BenjaminNeustadt requested changes
The tags have not been created yet(?)

2022-08-04 08:18 UTC, raphaella-rose approved these changes

2022-08-04 08:20 UTC, raphaella-rose commented
Could we edit the name of the pull to use our naming convention? :)

2022-08-04 09:37 UTC, BenjaminNeustadt approved these changes
Approved tags for hardcoded

2022-08-04 09:37 UTC, merged